import '../styles/DigitalPortfolioModal.css';

/**
 * DigitalPortfolioModal Component
 * 
 * Generates and downloads a professional PDF resume with QR code for the worker.
 * Uses jsPDF to create the PDF document client-side.
 * 
 * Features:
 * - Worker profile info (name, service, bio, location)
 * - QR code linking to profile verification
 * - Professional formatting
 * - One-click download
 */
const DigitalPortfolioModal = ({
  isOpen,
  workerName = 'Service Provider',
  serviceType = 'General Service',
  bio = 'Dedicated service professional',
  location = 'Baliwag, Bulacan',
  rating = 4.8,
  profilePhoto,
  gcashNumber = '09XXXXXXXXX',
  onClose,
}) => {
  if (!isOpen) return null;

  const generatePDF = async () => {
    try {
      // Dynamically import jsPDF to avoid build-time dependency issues
      const { jsPDF } = await import('jspdf');

      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      
      // Background color (light blue header)
      doc.setFillColor(37, 99, 235); // Blue
      doc.rect(0, 0, pageWidth, 50, 'F');

      // Title
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text('Digital Professional Portfolio', pageWidth / 2, 20, { align: 'center' });
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('GigLink Verified Professional', pageWidth / 2, 30, { align: 'center' });

      // Main content starts
      doc.setTextColor(0, 0, 0);
      let yPosition = 60;

      // Worker Name
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(workerName, 20, yPosition);
      yPosition += 8;

      // Service Type
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(`Service: ${serviceType}`, 20, yPosition);
      yPosition += 8;

      // Rating
      doc.text(`Rating: ⭐ ${rating}/5 (GigLink Verified)`, 20, yPosition);
      yPosition += 12;

      // Divider line
      doc.setDrawColor(200, 200, 200);
      doc.line(20, yPosition, pageWidth - 20, yPosition);
      yPosition += 8;

      // Bio Section
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('Professional Summary', 20, yPosition);
      yPosition += 6;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const bioLines = doc.splitTextToSize(bio, pageWidth - 40);
      doc.text(bioLines, 20, yPosition);
      yPosition += bioLines.length * 5 + 4;

      // Location Section
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('Service Location', 20, yPosition);
      yPosition += 6;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      doc.text(`📍 ${location}`, 20, yPosition);
      yPosition += 10;

      // Payment Method Section
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('Payment Method', 20, yPosition);
      yPosition += 6;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      doc.text(`💳 GCash: ${gcashNumber}`, 20, yPosition);
      yPosition += 10;

      // QR Code Section
      if (yPosition > pageHeight - 50) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('Verification QR Code', 20, yPosition);
      yPosition += 6;

      // Generate QR code image (using QR server API)
      const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(
        `GigLink Profile: ${workerName} - ${serviceType}`
      )}`;

      try {
        doc.addImage(qrCodeUrl, 'PNG', 20, yPosition, 50, 50);
      } catch (e) {
        doc.setFontSize(9);
        doc.text('QR Code: Visit giglink.app to verify profile', 20, yPosition);
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by GigLink • Trusted Service Marketplace', pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, pageHeight - 5, { align: 'center' });

      // Download PDF
      const fileName = `${workerName}_GigLink_Portfolio_${new Date().getFullYear()}.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error('PDF generation error:', error);
      alert('Could not generate PDF. Please try again.');
    }
  };

  return (
    <div className="portfolio-modal-overlay" role="dialog" aria-modal="true" aria-labelledby="portfolio-modal-title">
      <div className="portfolio-modal-card">
        <div className="portfolio-modal-header">
          <h3 id="portfolio-modal-title">Generate Digital Portfolio</h3>
          <button className="portfolio-modal-close" onClick={onClose}>✕</button>
        </div>

        <div className="portfolio-modal-body">
          <div className="portfolio-preview">
            <div className="preview-card">
              <div className="preview-header-section">
                <h2>{workerName}</h2>
                <p className="preview-service">{serviceType}</p>
                <p className="preview-rating">⭐ {rating}/5 - GigLink Verified</p>
              </div>

              <div className="preview-section">
                <h4>Professional Summary</h4>
                <p>{bio}</p>
              </div>

              <div className="preview-section">
                <h4>Service Location</h4>
                <p>📍 {location}</p>
              </div>

              <div className="preview-section">
                <h4>Payment Method</h4>
                <p>💳 GCash: {gcashNumber}</p>
              </div>

              <div className="preview-section qr-section">
                <h4>Verification QR Code</h4>
                <img 
                  src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(
                    `GigLink Profile: ${workerName} - ${serviceType}`
                  )}`}
                  alt="Profile QR Code"
                  className="preview-qr"
                />
              </div>

              <p className="preview-footer">
                Generated by GigLink • Trusted Service Marketplace
              </p>
            </div>
          </div>

          <div className="portfolio-info-box">
            <p>
              <strong>📄 PDF Resume:</strong> This professional portfolio will be downloaded as a PDF file that you can share with clients, print, or display online.
            </p>
            <p>
              <strong>🔐 QR Verification:</strong> The embedded QR code verifies your profile on GigLink, building trust with potential clients.
            </p>
            <p>
              <strong>💼 Professional Use:</strong> Use this portfolio in emails, social media, or print ads to establish your professional identity.
            </p>
          </div>
        </div>

        <div className="portfolio-modal-actions">
          <button className="portfolio-cancel-btn" onClick={onClose}>
            Cancel
          </button>
          <button className="portfolio-download-btn" onClick={generatePDF}>
            📥 Download PDF Portfolio
          </button>
        </div>
      </div>
    </div>
  );
};

export default DigitalPortfolioModal;
